### ISSUE TITLE
스프린트 1

### ISSUE THREAD

**Issue by jimin52** [jiphyeonjeon-42/backend-nest#10]
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/2
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/11
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/13
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/14
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/27
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/33
```
