### ISSUE TITLE
API 명세 작성

### ISSUE THREAD

**Issue by nyj001012** [jiphyeonjeon-42/backend-nest#44]
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/43
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/45
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/46
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/56
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/57
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/64
- [ ] https://github.com/jiphyeonjeon-42/backend-nest/issues/58
```
