### ISSUE TITLE
문서화

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend-nest#55]
```[tasklist]
### Tasks
- [ ] 프로젝트 실행 방법
- [ ] github pages 설정
- [ ] DTO 타입 정리
- [ ] 시퀀스 다이어그램 정리
- [ ] 코드 스타일 정리
```
